In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

from __future__ import print_function
from keras.models import Model
from keras.layers import Dense, Input
from keras.datasets import mnist
from keras.regularizers import l1
from keras.optimizers import Adam


Using TensorFlow backend.


In [2]:
n = 16
m = 16
a = [0] * n
for i in range(n):
    a[i] = [0] * m
print(a)
for i in range(n):
    a[i][i] = 1
a = np.squeeze( np.asarray(a))
print(type(a))


[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
<class 'numpy.ndarray'>


In [5]:
input_size = 16
#hidden_size = 128
code_size = 5
basepath = 'C:\\Users\\Dai\\Dropbox\\02 classes\\data mining\\homework\\HW4\\ReLu_singlehidden\\ex4\\'
initial_Theta1 = np.loadtxt(basepath+'initial_Theta1_5_try2.mat')
initial_Theta1=np.transpose(np.delete(initial_Theta1,1,axis=1))
initial_Theta2 = np.loadtxt(basepath+'initial_Theta2_5_try2.mat')
initial_Theta2=np.transpose(np.delete(initial_Theta2,1,axis=1))
input_img = Input(shape=(input_size,))
#hidden_1 = Dense(hidden_size, activation='relu')(input_img)
code = Dense(code_size, activation='relu')(input_img)
#hidden_2 = Dense(hidden_size, activation='relu')(code)
output_img = Dense(input_size, activation='sigmoid')(code)

autoencoder = Model(input_img, output_img)
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')
autoencoder.fit(a, a, epochs=200)


Epoch 1/200
16/16 [==============================] - 1s 32ms/step - loss: 0.7128
Epoch 2/200
16/16 [==============================] - 0s 251us/step - loss: 0.7118
Epoch 3/200
16/16 [==============================] - 0s 313us/step - loss: 0.7108
Epoch 4/200
16/16 [==============================] - 0s 251us/step - loss: 0.7098
Epoch 5/200
16/16 [==============================] - 0s 251us/step - loss: 0.7087
Epoch 6/200
16/16 [==============================] - 0s 188us/step - loss: 0.7077
Epoch 7/200
16/16 [==============================] - 0s 251us/step - loss: 0.7067
Epoch 8/200
16/16 [==============================] - 0s 251us/step - loss: 0.7057
Epoch 9/200
16/16 [==============================] - 0s 375us/step - loss: 0.7047
Epoch 10/200
16/16 [==============================] - 0s 188us/step - loss: 0.7038
Epoch 11/200
16/16 [==============================] - 0s 188us/step - loss: 0.7028
Epoch 12/200
16/16 [==============================] - 0s 251us/step - loss: 0.7018
Epoch 13/200
1

Epoch 100/200
16/16 [==============================] - 0s 313us/step - loss: 0.6263
Epoch 101/200
16/16 [==============================] - 0s 188us/step - loss: 0.6254
Epoch 102/200
16/16 [==============================] - 0s 251us/step - loss: 0.6246
Epoch 103/200
16/16 [==============================] - 0s 251us/step - loss: 0.6237
Epoch 104/200
16/16 [==============================] - 0s 251us/step - loss: 0.6228
Epoch 105/200
16/16 [==============================] - 0s 125us/step - loss: 0.6220
Epoch 106/200
16/16 [==============================] - 0s 251us/step - loss: 0.6211
Epoch 107/200
16/16 [==============================] - 0s 188us/step - loss: 0.6202
Epoch 108/200
16/16 [==============================] - 0s 125us/step - loss: 0.6194
Epoch 109/200
16/16 [==============================] - 0s 188us/step - loss: 0.6185
Epoch 110/200
16/16 [==============================] - 0s 125us/step - loss: 0.6176
Epoch 111/200
16/16 [==============================] - 0s 188us/step - loss:

Epoch 198/200
16/16 [==============================] - 0s 439us/step - loss: 0.5313
Epoch 199/200
16/16 [==============================] - 0s 125us/step - loss: 0.5302
Epoch 200/200
16/16 [==============================] - 0s 251us/step - loss: 0.5291


In [6]:
encoder = Model(input_img, code)
encoded_input = Input(shape=(code_size,))
decoder_layer = autoencoder.layers[-1]
decoder = Model(encoded_input, decoder_layer(encoded_input))

In [7]:
encoded_imgs = encoder.predict(a)
decoded_imgs = decoder.predict(encoded_imgs)

In [12]:
print(encoded_imgs)

[[0.         0.12223481 0.832626   0.23293619 0.34791657]
 [0.3209197  0.         0.7018976  0.         0.8804962 ]
 [0.6563195  0.25157037 0.3393637  0.         0.78096175]
 [0.71553296 0.         0.         0.02855713 0.        ]
 [0.49290738 0.13114348 0.65592855 0.         0.83119106]
 [0.         0.         0.41465503 0.         0.        ]
 [0.3992069  0.10107175 0.5582108  0.         0.        ]
 [0.04284032 0.         0.6869076  0.3051718  0.0699089 ]
 [0.         0.         0.         0.30164415 0.82219887]
 [0.         0.         0.         0.         0.6158521 ]
 [0.0619115  0.19055009 0.00131945 0.         0.63131654]
 [0.4445042  0.13595355 0.73383653 0.         0.        ]
 [0.         0.         0.66633725 0.         0.        ]
 [0.15102789 0.05888479 0.         0.         0.97046024]
 [0.6059508  0.16036546 0.8034556  0.         0.48231852]
 [0.         0.         0.41705012 0.         0.75867456]]


In [10]:
print(np.sum(a-decoded_imgs))

-84.20692798495293
